// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = 'driver' | 'passenger' | 'admin';
export type OrderType = 'passenger' | 'parcel';
export type OrderStatus = 'pending' | 'matched' | 'completed' | 'cancelled';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          telegram_id: string;
          role: UserRole;
          phone: string | null;
          full_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          telegram_id: string;
          role?: UserRole;
          phone?: string | null;
          full_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          telegram_id?: string;
          role?: UserRole;
          phone?: string | null;
          full_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          user_id: string;
          type: OrderType;
          from_city: string;
          to_city: string;
          scheduled_at: string;
          status: OrderStatus;
          details: Json;
          price: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: OrderType;
          from_city: string;
          to_city: string;
          scheduled_at: string;
          status?: OrderStatus;
          details?: Json;
          price?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: OrderType;
          from_city?: string;
          to_city?: string;
          scheduled_at?: string;
          status?: OrderStatus;
          details?: Json;
          price?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}

